Log reporter
mapbox/mapbox-events-ios pull request #26
Opened 2017-12-01 19:44 UTC by rclee

This adds a method to generate a view controller with a WKWebView to display event profiling information for debugging purposes.

2017-12-04 18:56 UTC, boundsj requested changes
Thanks! This feature will really help profile performance of this library.

In addition to the questions I asked in-line, I was wondering how the `readAndDisplayLogFileFromDate:viewController` method is intended to be invoked. I don't think `MMEEventLogger` is or ever should be public so it is not something a host SDK or application can use. I think that means we would need to add an API to `MMEEventsManager` and the host SDK/app would need to know that API exists and call it and it, in turn, would use `MMEEventLogger`. 

Injecting this profile/HTML view is going to be a bit awkward no matter what but I wonder about an internal, undocumented API that automatically finds the current, topmost view controller and presents using whatever that is. Alternatively, I suppose we could design an API that vends a web view and the host SDK/app can be responsible for adding that web view to the hierarchy.

2017-12-04 18:56 UTC, boundsj commented on MapboxMobileEvents/MMEEventLogReportViewController.m
> +    dispatch_async(dispatch_get_main_queue(), ^{
What is the purpose of marshaling to the main thread here? `viewDidLoad` would never be called in any other thread context, right?

2017-12-04 19:32 UTC, rclee commented
Great feedback! I'll look into adding these changes tonight. I figured the `MMEEventLogger` should probably remain private but since it was just for debugging purposes that we might be able to get away with it. In hindsight the design you described makes more sense. 

I'll look into implementing the API for finding the topmost view controller, that is certainly cleaner than the current implementation. Thanks!

2017-12-04 19:32 UTC, rclee commented on MapboxMobileEvents/MMEEventLogReportViewController.m
> +    dispatch_async(dispatch_get_main_queue(), ^{
Yes, you're right--just a oversight on my part. Thanks for catching that.

2017-12-07 22:19 UTC, boundsj approved these changes
Looks good to me!

2017-12-07 22:19 UTC, boundsj commented on MapboxMobileEvents/MMEConstants.m
> +NSString * const MMELoggerHTML = @"<html><head><script type='text/javascript' src='https://www.gstatic.com/charts/loader.js'></script><script type='text/javascript'>google.charts.load('current', {'pa
Thanks for putting this back and sorry for waffling from [my original comment](https://github.com/mapbox/mapbox-events-ios/pull/26/files/9956e4b2cb1e5fab798568b2ed2280c87e32bba9#r154723787). No need to change anything here but, in the future to make this more readable and easier to update, we could code generate this string from an html file that is in this project but not shipped as part of this library.

2017-12-07 22:32 UTC, merged