Support Swift Package Manager for Xcode 12.5
mapbox/mapbox-events-ios pull request #277
Opened 2021-02-05 15:26 UTC by OdNairy

New Swift 5.3 (shipped in Xcode 12.5) introduced additional constraints over SPM setup.

Changes: 
* Change headers layout to produce public headers folder without subfolders (SPM requirement in Xcode 12.5)
* Disable twitter link as it breaks pod lint process (CocoaPods/CocoaPods#10291)
* Updated preprocessor target definitions 

Closes #276

2021-02-05 17:00 UTC, alfwatt requested changes
Overall looks like a good change, want to check with @mapbox/core-telemetry about the umbrella header imports

2021-02-05 17:00 UTC, alfwatt commented on Sources/MapboxMobileEvents/include/MapboxMobileEvents.h
> +#import "MMEConstants.h"
@OdNairy this changes looks suspicious, the umbrella header should have the <FrameworkRelative/Header.h> import form cc: @mapbox/core-telemetry

2021-02-05 22:34 UTC, OdNairy commented on Sources/MapboxMobileEvents/include/MapboxMobileEvents.h
> +#import "MMEConstants.h"
SPM doesn't allow folders in include/ folder with public headers since Xcode 12.5. 
That's why I've made this PR.

2021-02-08 07:52 UTC, mr1sunshine approved these changes

2021-02-08 08:27 UTC, merged