CarPlay events.
mapbox/mapbox-events-ios pull request #64
Opened 2018-08-27 20:21 UTC by vincethecoder

Provided events to permit carplay related telemetry data.

2018-08-27 21:31 UTC, rclee submitted a review, later dismissed
Looks good! 👍

2018-08-29 14:22 UTC, rclee requested changes

2018-08-29 14:26 UTC, rclee commented on MapboxMobileEvents/MMEEventsManager.m
> +        [attributesWithTimestamp addEntriesFromDictionary:attributes];
Thinking about this again.. I'd prefer if we could stick with the first method of adding `created` timestamp in the client SDK if at all possible. EventsSDK should have as little knowledge of the events as possible.

2018-08-29 20:56 UTC, vincethecoder commented
@rclee reverted the date attribute field. ✅

2018-08-29 20:57 UTC, rclee approved these changes

2018-08-30 14:52 UTC, merged